
title: Srikar Madarapu
email: Madarapu.Srikar@gmail.com
description:  #> # this means to ignore newlines until "baseurl:"
  - Udacity Self-Driving Car Engineer Nanodegree Term - 1 Feb 2019 <br>
  - Bachelor's in Computer Science Engineering <br>
baseurl: "" # the subpath of your site, e.g. /blog
#permalink: /:year/:month/:day/:title.html

url: "../" # the base hostname & protocol for your site
twitter_username:  Madarapu_srikar
github_username:   srikar8
linkedin_username: srikar8

# Build settings
markdown: kramdown
